baseURL: https://jaredpetersen.github.io
languageCode: en-us
title: Jared Petersen
theme: jaredpetersen
copyright: 2021 Jared Petersen. All rights reserved.

params:
  description: Personal website and blog for Jared Petersen covering a range of software engineering topics
  emoji: 🚜

  social:
    - type: GitHub
      url: https://github.com/jaredpetersen
    - type: StackOverflow
      url: https://stackoverflow.com/users/7583677/jared-petersen
    - type: LinkedIn
      url: https://www.linkedin.com/in/petersenjared
    - type: Instagram
      url: https://instagram.com/jaredtpetersen
    - type: Twitter
      url: https://twitter.com/jaredtpetersen
    - type: Email
      url: mailto:jaredtoddpetersen@gmail.com

googleAnalytics: G-8B0VL7E1R0

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false

disableKinds:
  - RSS

permalinks:
  blog: /blog/:year/:month/:slug/
